nelmio_cors:
    paths:
        '^/api':
            origin_regex: true
            allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
            allow_headers: ['Content-Type', 'Authorization', 'X-Total-Count']
            expose_headers: ['Link']
            max_age: 3600
